// EN 18031 — Terms and definitions (Clause 3), BS EN 18031-1/2/3:2024.
//
// AUTO-GENERATED by parse-definitions.mjs. Verbatim normative definitions
// (Notes/Examples omitted). Injected as grounding context so the AI interprets
// standard terms exactly as defined — not from prior knowledge. Some terms (e.g.
// "security function") are defined differently per standard; each variant lists
// the standards it applies to.
//
// To regenerate: node parse-definitions.mjs

export type DefinitionVariant = {
  stds: number[]; // EN 18031 parts this definition applies to (1, 2, 3)
  clause: string;
  definition: string;
};

export const DEFINITIONS: Record<string, DefinitionVariant[]> = {
  "access control mechanism": [
    { stds: [1, 2, 3], clause: "EN 18031-1 §3.1", definition: "equipment functionality to grant, restrict or deny access to specific equipment’s resources" },
  ],
  "assessment objective": [
    { stds: [1, 2, 3], clause: "EN 18031-1 §3.5", definition: "statement, provided as part of the assessment input, which defines the reasons for performing the assessment" },
  ],
  "authentication": [
    { stds: [1, 2, 3], clause: "EN 18031-1 §3.2", definition: "provision of assurance that an entity is who or what it claims to be" },
  ],
  "authentication mechanism": [
    { stds: [1, 2, 3], clause: "EN 18031-1 §3.3", definition: "equipment functionality to verify that an entity is who or what it claims to be" },
  ],
  "authenticator": [
    { stds: [1, 2, 3], clause: "EN 18031-1 §3.4", definition: "something known or possessed, and controlled by an entity that is used for authentication" },
  ],
  "best practice": [
    { stds: [1, 2, 3], clause: "EN 18031-1 §3.6", definition: "measures that have been shown to provide appropriate security for the corresponding use case" },
  ],
  "brute force attack": [
    { stds: [1, 2, 3], clause: "EN 18031-1 §3.7", definition: "attack on a cryptosystem that employs a trial-and-error search of a set of keys, passwords or other data" },
  ],
  "communication mechanism": [
    { stds: [1, 2, 3], clause: "EN 18031-1 §3.8", definition: "equipment functionality that allows communication via a machine interface" },
  ],
  "confidential cryptographic key": [
    { stds: [1, 2, 3], clause: "EN 18031-1 §3.9", definition: "confidential security parameter, excluding passwords, which is used in the operation of a cryptographic algorithm or cryptographic protocol" },
  ],
  "confidential financial data": [
    { stds: [3], clause: "EN 18031-3 §3.10", definition: "financial data whose disclosure can lead to fraud" },
  ],
  "confidential financial function configuration": [
    { stds: [3], clause: "EN 18031-3 §3.11", definition: "financial function configuration whose disclosure can lead to fraud" },
  ],
  "confidential network function configuration": [
    { stds: [1], clause: "EN 18031-1 §3.10", definition: "network function configuration whose disclosure can harm the network or its functioning or can lead to misuse of network resources" },
  ],
  "confidential personal information": [
    { stds: [2], clause: "EN 18031-2 §3.10", definition: "personal information whose disclosure can compromise the user’s or subscriber’s privacy" },
  ],
  "confidential privacy function configuration": [
    { stds: [2], clause: "EN 18031-2 §3.11", definition: "privacy function configuration whose disclosure can compromise the user’s or subscriber’s privacy" },
  ],
  "confidential security parameter": [
    { stds: [1], clause: "EN 18031-1 §3.11", definition: "security parameter whose disclosure can harm the network or its functioning or can lead to misuse of network resources" },
    { stds: [2], clause: "EN 18031-2 §3.12", definition: "security parameter whose disclosure can compromise the user’s or subscriber’s privacy" },
  ],
  "confidential security parameters": [
    { stds: [3], clause: "EN 18031-3 §3.12", definition: "security parameter whose disclosure can lead to fraud" },
  ],
  "denial of service": [
    { stds: [1, 2, 3], clause: "EN 18031-1 §3.12", definition: "prevention or interruption of authorized access to an equipment resource or the delaying of the equipment operations and functions" },
  ],
  "device": [
    { stds: [1, 2, 3], clause: "EN 18031-1 §3.13", definition: "product external to the equipment" },
  ],
  "entity": [
    { stds: [1, 2, 3], clause: "EN 18031-1 §3.14", definition: "user, device, equipment or service" },
  ],
  "entropy": [
    { stds: [1, 2, 3], clause: "EN 18031-1 §3.15", definition: "measure of the disorder, randomness or variability in a closed system" },
  ],
  "external interface": [
    { stds: [1, 2, 3], clause: "EN 18031-1 §3.16", definition: "interface of an equipment that is accessible from outside the equipment." },
  ],
  "factory default state": [
    { stds: [1, 2, 3], clause: "EN 18031-1 §3.17", definition: "defined state where the configuration settings and configuration of the equipment is set to initial values" },
  ],
  "financial asset": [
    { stds: [3], clause: "EN 18031-3 §3.19", definition: "sensitive financial data or confidential financial data or sensitive financial function configuration or confidential financial function configuration or financial functions" },
  ],
  "financial data": [
    { stds: [3], clause: "EN 18031-3 §3.20", definition: "data that represents, provides information about, or is processed for transferring money, monetary assets or virtual currencies [35]" },
  ],
  "financial function": [
    { stds: [3], clause: "EN 18031-3 §3.21", definition: "equipment’s functionality that processes financial data" },
  ],
  "financial function configuration": [
    { stds: [3], clause: "EN 18031-3 §3.22", definition: "data processed by the equipment that defines the behaviour of the equipment’s financial functions" },
  ],
  "hard-coded": [
    { stds: [1, 2, 3], clause: "EN 18031-1 §3.18", definition: "software development practice of embedding data directly into the source code of a program or other executable object" },
  ],
  "initialization": [
    { stds: [1, 2, 3], clause: "EN 18031-1 §3.19", definition: "process that configures the network connectivity of the equipment for operation" },
  ],
  "interface": [
    { stds: [1, 2, 3], clause: "EN 18031-1 §3.20", definition: "shared boundary across which entities exchange information" },
  ],
  "justification": [
    { stds: [1, 2, 3], clause: "EN 18031-1 §3.21", definition: "documented information providing evidence that a claim is true under the assumption of common expertise" },
  ],
  "log data": [
    { stds: [2, 3], clause: "EN 18031-2 §3.23", definition: "record(s) of certain events (of processes) on a computing equipment" },
  ],
  "logging mechanism": [
    { stds: [2, 3], clause: "EN 18031-2 §3.24", definition: "equipment functionality to log internal activities" },
  ],
  "machine interface": [
    { stds: [1, 2, 3], clause: "EN 18031-1 §3.22", definition: "external interface between the equipment and a service or device" },
  ],
  "network asset": [
    { stds: [1], clause: "EN 18031-1 §3.23", definition: "sensitive network function configuration or confidential network function configuration or network functions" },
  ],
  "network equipment": [
    { stds: [1], clause: "EN 18031-1 §3.24", definition: "equipment that exchanges data between different networks used to permanently connect directly other devices to the internet" },
  ],
  "network function": [
    { stds: [1], clause: "EN 18031-1 §3.25", definition: "equipment’s functionality to provide or utilize network resources by itself" },
  ],
  "network function configuration": [
    { stds: [1], clause: "EN 18031-1 §3.26", definition: "data processed by the equipment that defines the behaviour of the equipment’s network function" },
  ],
  "network interface": [
    { stds: [1, 2, 3], clause: "EN 18031-1 §3.27", definition: "external interface enabling the equipment to have or provide access to a network" },
  ],
  "operational state": [
    { stds: [1, 2], clause: "EN 18031-1 §3.28", definition: "state in which the equipment is functioning normally according to the intended equipment functionality [35] and within its intended operational environment of use" },
    { stds: [3], clause: "EN 18031-3 §3.31", definition: "state in which the equipment is functioning normally according its intended equipment functionality [36] and within its intended operational environment of use" },
  ],
  "optional service": [
    { stds: [1, 2], clause: "EN 18031-1 §3.29", definition: "service which is not necessary to setup the equipment, and which is not part of the basic functionality but is still relevant for the intended equipment functionality [35] and is delivered as part of the factory default." },
    { stds: [3], clause: "EN 18031-3 §3.32", definition: "services which are not necessary to setup the equipment, and which are not part of the basic functionality but are still relevant for the intended equipment functionality [36] and are delivered as part of the factory default." },
  ],
  "password": [
    { stds: [1, 2, 3], clause: "EN 18031-1 §3.30", definition: "sequence of characters (letters, numbers, or other symbols) used to authenticate an entity" },
  ],
  "personal information": [
    { stds: [2], clause: "EN 18031-2 §3.30", definition: "personal data [40], traffic data [41] or location data [41]" },
  ],
  "personal information of special categories": [
    { stds: [2], clause: "EN 18031-2 §3.31", definition: "personal information that is genetic data, biometric data for the purpose of uniquely identifying a natural person, data concerning health or data concerning a natural person's sex life or sexual orientation or that reveals racial or ethnic origin, political opinions, religious or philosophical beliefs, or trade union membership" },
  ],
  "privacy asset": [
    { stds: [2], clause: "EN 18031-2 §3.32", definition: "sensitive personal information or confidential personal information or sensitive privacy function configuration or confidential privacy function configuration or privacy functions" },
  ],
  "privacy function": [
    { stds: [2], clause: "EN 18031-2 §3.33", definition: "equipment’s functionality that processes personal information" },
  ],
  "privacy function configuration": [
    { stds: [2], clause: "EN 18031-2 §3.34", definition: "data processed by the equipment that defines the behaviour of the equipment’s privacy functions" },
  ],
  "public security parameter": [
    { stds: [1, 2, 3], clause: "EN 18031-1 §3.31", definition: "sensitive security parameter that is not confidential" },
  ],
  "resilient": [
    { stds: [1, 2, 3], clause: "EN 18031-1 §3.32", definition: "able to anticipate, withstand, recover from, and adapt to adverse conditions, stresses, attacks, or compromises on systems that use or are enabled by cyber resources." },
  ],
  "resource": [
    { stds: [1, 2, 3], clause: "EN 18031-1 §3.34", definition: "functional unit or data item needed to perform required operations" },
  ],
  "risk": [
    { stds: [1, 2, 3], clause: "EN 18031-1 §3.33", definition: "combination of the probability of occurrence of harm and the severity of that harm" },
  ],
  "security asset": [
    { stds: [1, 2, 3], clause: "EN 18031-1 §3.35", definition: "sensitive security parameter or confidential security parameter or security function" },
  ],
  "security function": [
    { stds: [1], clause: "EN 18031-1 §3.36", definition: "functionality on the equipment that is relevant to protect it from harming the network or its functioning or misusing network resources" },
    { stds: [2], clause: "EN 18031-2 §3.40", definition: "measure on the equipment that ensures that the personal data and the privacy of the user and of the subscriber are protected" },
    { stds: [3], clause: "EN 18031-3 §3.39", definition: "functionality on the equipment that protects security assets or financial assets from being misused for fraud" },
  ],
  "security parameter": [
    { stds: [1, 2, 3], clause: "EN 18031-1 §3.37", definition: "data processed by the equipment that defines the behaviour of the equipment‘s security function" },
  ],
  "security strength": [
    { stds: [1, 2, 3], clause: "EN 18031-1 §3.38", definition: "number associated with the amount of work that is required to break a cryptographic algorithm or system" },
  ],
  "security update": [
    { stds: [1, 2, 3], clause: "EN 18031-1 §3.41", definition: "software update that addresses security vulnerabilities through software patches or other mitigations" },
  ],
  "sensitive financial data": [
    { stds: [3], clause: "EN 18031-3 §3.42", definition: "financial data whose manipulation can lead to fraud" },
  ],
  "sensitive financial function configuration": [
    { stds: [3], clause: "EN 18031-3 §3.43", definition: "financial function configuration whose unauthorized modification can lead to fraud" },
  ],
  "sensitive network function configuration": [
    { stds: [1], clause: "EN 18031-1 §3.39", definition: "network function configuration whose manipulation can harm the network or its functioning or can lead to misuse of network resources" },
  ],
  "sensitive personal information": [
    { stds: [2], clause: "EN 18031-2 §3.43", definition: "personal information whose manipulation can compromise the user’s or subscriber’s privacy" },
  ],
  "sensitive privacy function configuration": [
    { stds: [2], clause: "EN 18031-2 §3.44", definition: "privacy function configuration whose manipulation can compromise the user’s or subscriber’s privacy" },
  ],
  "sensitive security parameter": [
    { stds: [1], clause: "EN 18031-1 §3.40", definition: "security parameter whose manipulation can harm the network or its functioning or can lead to misuse of network resources" },
    { stds: [2], clause: "EN 18031-2 §3.45", definition: "security parameter whose manipulation can compromise the user’s or subscriber’s privacy" },
  ],
  "sensitive security parameters": [
    { stds: [3], clause: "EN 18031-3 §3.44", definition: "security parameter whose manipulation can lead to fraud" },
  ],
  "software": [
    { stds: [1, 2, 3], clause: "EN 18031-1 §3.42", definition: "assembly of programs, procedures, rules, documentation, and data, pertaining to the operation of an equipment" },
  ],
  "storage mechanism": [
    { stds: [1, 2, 3], clause: "EN 18031-1 §3.43", definition: "equipment functionality that allows to store information" },
  ],
  "update mechanism": [
    { stds: [1, 2, 3], clause: "EN 18031-1 §3.44", definition: "equipment functionality that allows to change equipment’s software" },
  ],
  "user interface": [
    { stds: [1, 2, 3], clause: "EN 18031-1 §3.45", definition: "external interface between the equipment and a user" },
  ],
  "vulnerability": [
    { stds: [1, 2, 3], clause: "EN 18031-1 §3.46", definition: "weakness, design, or implementation error that can lead to an unexpected, undesirable event compromising the security of the equipment, network, application, or protocol involved" },
  ],
};

// Render definitions as a compact grounding block. If `std` is given, only the
// variant applicable to that standard is shown per term. If `terms` is given,
// only those terms are included.
export function definitionsText(std?: 1 | 2 | 3, termList?: string[]): string {
  const keys = termList
    ? termList.map((t) => t.toLowerCase()).filter((t) => t in DEFINITIONS)
    : Object.keys(DEFINITIONS);
  const out: string[] = [];
  for (const k of keys) {
    const variants = DEFINITIONS[k];
    const v = std ? variants.find((x) => x.stds.includes(std)) : variants[0];
    if (!v) continue;
    out.push(`- ${k} (${v.clause}): ${v.definition}`);
  }
  return out.join("\n");
}
